language_instruction: move the apple to the plate
action_horizon: 40
embodiment_tag: NEW_EMBODIMENT
video_backend: decord
modality_config_path: isaaclab_arena_gr00t/embodiments/g1/g1_sim_wbc_data_gr00t_n_1_7_config.py
policy_joints_config_path: isaaclab_arena_gr00t/embodiments/g1/gr00t_43dof_joint_space.yaml
action_joints_config_path: isaaclab_arena_gr00t/embodiments/g1/43dof_joint_space.yaml
state_joints_config_path: isaaclab_arena_gr00t/embodiments/g1/43dof_joint_space.yaml
action_chunk_length: 40
pov_cam_name_sim: robot_head_cam_rgb
task_mode_name: g1_locomanipulation
bilateral_mirror: true
