# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Write environment graph specs to YAML."""

from __future__ import annotations

import re
import yaml
from pathlib import Path
from typing import Any

from isaaclab_arena.environment_spec.arena_env_graph_spec import ArenaEnvGraphSpec

DEFAULT_AGENTIC_OUTPUT_DIR = Path("isaaclab_arena_environments/agent_generated")


def safe_filename_stem(name: str) -> str:
    """Return a filesystem-safe stem derived from an env name."""
    stem = re.sub(r"[^\w.-]+", "_", name).strip("._")
    return stem or "unnamed_env"


def env_graph_spec_path(env_name: str, out_dir: Path) -> Path:
    """Return the default graph-spec YAML path for ``env_name`` under ``out_dir``."""
    return out_dir / f"{safe_filename_stem(env_name)}.yaml"


def generate_env_readme(graph_spec: ArenaEnvGraphSpec, yaml_path: Path) -> str:
    """Generate a rich environment README cheatsheet markdown."""
    env_name = graph_spec.env_name
    yaml_rel = str(yaml_path.resolve()) if yaml_path.is_absolute() else f"/workspaces/isaaclab_arena/{yaml_path}"
    out_dir_rel = (
        str(yaml_path.parent.resolve())
        if yaml_path.parent.is_absolute()
        else f"/workspaces/isaaclab_arena/{yaml_path.parent}"
    )
    eval_dir = f"/workspaces/isaaclab_arena/eval_output/{safe_filename_stem(graph_spec.env_name)}_eval"

    embodiment_name = graph_spec.embodiment.registry_name if graph_spec.embodiment else "N/A"
    background_name = graph_spec.background.registry_name if graph_spec.background else "N/A"
    objects_list = [f"`{obj.id}` (`{obj.registry_name}`)" for obj in graph_spec.objects]
    objects_str = ", ".join(objects_list) if objects_list else "None"
    task_desc = graph_spec.task.description if graph_spec.task else "Custom manipulation task"
    task_comp = graph_spec.task.composition if graph_spec.task else "atomic"

    asset_names = [obj.registry_name for obj in graph_spec.objects]
    asset_render_args = " ".join(asset_names) if asset_names else ""

    content = f"""# Environment: `{env_name}`

Automated environment specification generated by **IsaacLab-Arena Active Inference Agent**.

---

## 📋 Environment Specification Summary

* **Task Description**: {task_desc}
* **Task Composition**: `{task_comp}`
* **Embodiment**: `{embodiment_name}`
* **Background Anchor**: `{background_name}`
* **Scene Objects**: {objects_str}
* **Spec YAML**: [`{yaml_path.name}`]({yaml_path.name})

---

## 🚀 Commands Cheatsheet

### 1. Run Policy Evaluation (Zero-Action Policy)

#### Interactive 3D GUI Window (Omniverse Kit Viewport):
```bash
xhost +local:root 2>/dev/null || xhost +local:docker 2>/dev/null

docker exec -it \\
  -e DISPLAY="$DISPLAY" \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena/evaluation/policy_runner.py \\
  --policy_type isaaclab_arena.policy.zero_action_policy.ZeroActionPolicy \\
  --viz kit \\
  --num_steps 300 \\
  --num_envs 1 \\
  --enable_cameras \\
  --env_graph_spec_yaml {yaml_rel} \\
  --output_base_dir {eval_dir}
```

#### Headless Mode (Terminal Physics & Video Recording):
```bash
docker exec -it \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena/evaluation/policy_runner.py \\
  --policy_type isaaclab_arena.policy.zero_action_policy.ZeroActionPolicy \\
  --headless \\
  --num_steps 300 \\
  --num_envs 1 \\
  --enable_cameras \\
  --env_graph_spec_yaml {yaml_rel} \\
  --output_base_dir {eval_dir}
```

#### WebRTC Browser Streaming (View 3D Viewport in Chrome/Firefox):
```bash
docker exec -it \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena/evaluation/policy_runner.py \\
  --policy_type isaaclab_arena.policy.zero_action_policy.ZeroActionPolicy \\
  --livestream 1 \\
  --num_steps 300 \\
  --num_envs 1 \\
  --enable_cameras \\
  --env_graph_spec_yaml {yaml_rel} \\
  --output_base_dir {eval_dir}
```
*Open your browser at `http://localhost:8211/streaming/client/` to view and control the simulation.*

---

### 2. Fast PhysX Build & Simulation Rollout

#### Interactive 3D GUI (Isaac Sim Kit Viewport):
```bash
xhost +local:root 2>/dev/null || xhost +local:docker 2>/dev/null

docker exec -it \\
  -e DISPLAY="$DISPLAY" \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena_examples/agentic_environment_generation/environment_generation_runner.py \\
  --mode build \\
  --viz kit \\
  --num_steps 500 \\
  --env_graph_spec_yaml {yaml_rel}
```

#### Headless Mode:
```bash
docker exec -it \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena_examples/agentic_environment_generation/environment_generation_runner.py \\
  --mode build \\
  --headless \\
  --num_steps 200 \\
  --env_graph_spec_yaml {yaml_rel}
```

---

### 3. Refine or Modify this Environment (Active Inference Derivation)

To derive a new version or modify objects/relations with conversational feedback:

```bash
docker exec -it \\
  -e OPENROUTER_API_KEY="$OPENROUTER_API_KEY" \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena_examples/agentic_environment_generation/environment_generation_runner.py \\
  --mode resolve \\
  --model "anthropic/claude-sonnet-4.5" \\
  --base_spec {yaml_rel} \\
  --feedback "Your refinement instruction here..." \\
  --out_dir {out_dir_rel}_refined
```

---

### 4. Render Asset Thumbnails

To render high-resolution PNG previews for the assets in this scene:

```bash
docker exec -it \\
  isaaclab_arena-latest /isaac-sim/python.sh \\
  isaaclab_arena_examples/tools/render_asset_thumbnails.py \\
  --assets {asset_render_args} \\
  --out_dir /workspaces/isaaclab_arena/eval_output/asset_thumbnails
```

---

### 5. Neo4j LPG Knowledge Graph Lineage Query

To inspect this environment and its lineage relationships in Neo4j Cypher:

```cypher
MATCH (e:EnvironmentGraph {{name: "{env_name}"}})
OPTIONAL MATCH (e)-[:HAS_EMBODIMENT]->(emb)
OPTIONAL MATCH (e)-[:HAS_TERRAIN]->(bg)
OPTIONAL MATCH (e)-[:CONTAINS_OBJECT]->(obj)
OPTIONAL MATCH (e)-[r:WAS_DERIVED_FROM*]->(parent:EnvironmentGraph)
RETURN e, emb, bg, collect(DISTINCT obj), parent
```
"""
    return content.strip() + "\n"


def write_env_graph_spec(graph_spec: ArenaEnvGraphSpec, out_dir: Path) -> Path:
    """Dump an environment graph spec to YAML and generate an automated README cheatsheet."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = env_graph_spec_path(graph_spec.env_name, out_dir)
    graph_spec.write_yaml(path)

    # Automatically generate README cheatsheet
    readme_path = out_dir / "README.md"
    readme_content = generate_env_readme(graph_spec, path)
    readme_path.write_text(readme_content, encoding="utf-8")

    return path


def write_env_graph_dict(data: dict[str, Any], out_dir: Path) -> Path:
    """Dump a parsed agent response dict to YAML under ``out_dir`` (no validation)."""
    env_name = data.get("env_name", "unnamed_env")
    if not isinstance(env_name, str):
        env_name = "unnamed_env"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = env_graph_spec_path(env_name, out_dir)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return path

