import { fireEvent, render, screen } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { normalizeGraph } from './graph-model';
import { GraphInspector } from './graph-inspector';
it('inspects sentinels, follows edge endpoints, paginates loaded edges and rejects nonfinite coordinate edits', () => {
  const graph = normalizeGraph({ nodes: [{ id: '__proto__', label: '<img src=x>', role: 'reifier', properties: '[truncated]' }], edges: Array.from({ length: 28 }, (_, i) => ({ id: `e${i}`, source: '__proto__', target: '__proto__', label: 'on', properties: null })) });
  const onSelect = vi.fn(), moveNode = vi.fn();
  const handle = { moveNode, nudgeNode: vi.fn(), setPinned: vi.fn() } as any;
  const props = { graph, selection: { kind: 'node' as const, id: '__proto__' }, onSelect, hidden: true, onReveal: vi.fn(), mode: '3d' as const, handle, snapshot: { positions: new Map([['__proto__', { x: 1, y: 2, z: 3 }]]), pins: new Set<string>(), frozen: true }, step: 10 };
  const { rerender } = render(<GraphInspector {...props} />);
  expect(screen.getByText('[truncated]')).toBeTruthy();
  expect(screen.getByText('Hidden by filters')).toBeTruthy();
  expect(screen.getAllByRole('button', { name: /^Inspect relationship/ })).toHaveLength(25);
  fireEvent.click(screen.getByRole('button', { name: 'Next loaded relationships' }));
  expect(screen.getAllByRole('button', { name: /^Inspect relationship/ })).toHaveLength(3);
  fireEvent.change(screen.getByLabelText('Layout X'), { target: { value: 'Infinity' } });
  fireEvent.click(screen.getByRole('button', { name: 'Apply coordinates' }));
  expect(moveNode).not.toHaveBeenCalled();
  expect(screen.getByRole('alert').textContent).toContain('finite');
  fireEvent.change(screen.getByLabelText('Layout X'), { target: { value: '4.5' } });
  fireEvent.click(screen.getByRole('button', { name: 'Apply coordinates' }));
  expect(moveNode).toHaveBeenCalledWith('__proto__', { x: 4.5, y: 2, z: 3 });
  fireEvent.click(screen.getByRole('button', { name: 'Nudge up (view-relative)' }));
  expect(handle.nudgeNode).toHaveBeenCalledWith('__proto__', 0, -10, 0);
  fireEvent.click(screen.getByRole('button', { name: 'Nudge forward (view-relative)' }));
  expect(handle.nudgeNode).toHaveBeenLastCalledWith('__proto__', 0, 0, 10);
  rerender(<GraphInspector {...props} selection={{ kind: 'edge', id: 'e0' }} />);
  fireEvent.click(screen.getByRole('button', { name: /^Source:/ }));
  expect(onSelect).toHaveBeenCalledWith({ kind: 'node', id: '__proto__' });
});
it('copies literal IDs safely and leaves hostile labels and sentinels as inert text', async () => {
  const fetcher = vi.spyOn(globalThis, 'fetch').mockRejectedValue(new Error('Network forbidden'));
  const writeText = vi.fn().mockResolvedValue(undefined);
  const previous = Object.getOwnPropertyDescriptor(navigator, 'clipboard');
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } });
  const graph = normalizeGraph({ nodes: [{ id: '__proto__', label: '<img src="https://invalid.test/track">', role: 'object', properties: '[redacted]' }], edges: [] });
  render(<GraphInspector graph={graph} selection={{ kind: 'node', id: '__proto__' }} onSelect={vi.fn()} hidden={false} onReveal={vi.fn()} mode="table" handle={null} snapshot={{ positions: new Map(), pins: new Set(), frozen: true }} step={10} />);
  fireEvent.click(screen.getByRole('button', { name: 'Copy ID' }));
  await screen.findByText('ID copied.');
  expect(writeText).toHaveBeenCalledWith('__proto__');
  writeText.mockRejectedValueOnce(new Error('Denied'));
  fireEvent.click(screen.getByRole('button', { name: 'Copy ID' }));
  await screen.findByText(/Clipboard unavailable/);
  expect(document.querySelector('img')).toBeNull();
  expect(screen.getByText('[redacted]')).toBeTruthy();
  expect(fetcher).not.toHaveBeenCalled();
  fetcher.mockRestore();
  if (previous) Object.defineProperty(navigator, 'clipboard', previous); else Reflect.deleteProperty(navigator, 'clipboard');
});
