#!/usr/bin/env node
/** Offline browser walkthrough; OS egress denial must precede package imports. */
import net from 'node:net';
import os from 'node:os';
import { mkdir, writeFile, realpath, readFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';

assert.deepEqual(Object.keys(os.networkInterfaces()).filter(name => name !== 'lo'), []);
await new Promise((resolve, reject) => {
 const socket = net.connect({ host: '198.18.0.1', port: 9 });
 socket.setTimeout(1000, () => { socket.destroy(); reject(Error('Inconclusive isolation probe')); });
 socket.on('connect', () => { socket.destroy(); reject(Error('Egress permitted')); });
 socket.on('error', error => ['ENETUNREACH', 'EHOSTUNREACH'].includes(error.code) ? resolve() : reject(Error('Unexpected isolation result')));
});
const { chromium } = await import('@playwright/test');
const output = process.env.PREVIEW_EVIDENCE ?? '/tmp/preview-browser-evidence';
const artifact = await realpath(process.argv[2] ?? '/tmp/arena-ui-preview-dist/arena-workflow-preview.html');
assert.equal(dirname(artifact), await realpath('/tmp/arena-ui-preview-dist'));
const artifactUrl = pathToFileURL(artifact).href;
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--disable-background-networking', '--disable-component-update', '--disable-sync', '--no-first-run'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1080 }, serviceWorkers: 'block' });

const errors = [], denied = [], screens = [];
await context.addInitScript(() => {
 window.__previewBlockedEffects = [];
 const deny = effect => { window.__previewBlockedEffects.push(effect); throw new Error(`Offline preview forbids ${effect}`); };
 for (const name of ['RTCPeerConnection', 'webkitRTCPeerConnection', 'Worker', 'SharedWorker', 'EventSource']) Object.defineProperty(window, name, { configurable: true, value: class { constructor() { deny(name); } } });
 for (const name of ['getItem', 'setItem', 'removeItem', 'clear', 'key']) Storage.prototype[name] = function () { deny(`Storage.${name}`); };
});
const historicalImages = [];
await context.route('**/*', route => {
 const url = route.request().url();
 if (url === artifactUrl || url.startsWith('data:')) return route.continue();
 denied.push({ method: route.request().method(), protocol: new URL(url).protocol });
 return route.abort();
});
await context.routeWebSocket('**/*', socket => { denied.push({ method: 'WEBSOCKET' }); socket.close(); });
await context.tracing.start({ screenshots: true, snapshots: true });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const nav = page.getByRole('navigation', { name: 'Preview navigation' });
async function shot(name) { await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({ path: `${output}/${name}.png`, fullPage: true }); screens.push(name); }
async function primaryHoverContrast() {
 const button = page.getByRole('banner', { name: 'Preview top bar' }).getByRole('button', { name: 'Sign up', exact: true });
 await button.hover();
 const ratio = await button.evaluate(element => {
  const style = getComputedStyle(element);
  const luminance = color => {
   const channels = color.match(/[\d.]+/g).slice(0, 3).map(Number).map(value => value / 255).map(value => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4);
   return channels[0] * .2126 + channels[1] * .7152 + channels[2] * .0722;
  };
  const values = [luminance(style.color), luminance(style.backgroundColor)].sort((a, b) => a - b);
  return (values[1] + .05) / (values[0] + .05);
 });
 assert.ok(ratio >= 4.5, `Primary button hover text contrast ${ratio} is below 4.5`);
 await page.mouse.move(0, 0);
 return ratio;
}
try {
 await page.goto(pathToFileURL(artifact).href);
 await page.getByRole('heading', { name: 'Environment', exact: true }).waitFor();
 assert.match(await page.locator('.preview-banner').innerText(), /Example data/);
 const top = page.getByRole('banner', { name: 'Preview top bar' });
 const sidebar = page.getByRole('complementary', { name: 'Workspace sidebar' });
 const themeSwitch = top.getByRole('switch', { name: 'Dark mode', exact: true });
 await top.getByText('Preview v7', { exact: true }).waitFor();
 assert.equal(await top.getByRole('button', { name: /left sidebar/ }).count(), 0);
 assert.equal(await themeSwitch.getAttribute('aria-checked'), 'true');
 await top.getByRole('img', { name: 'Cybernetic-Physics', exact: true }).waitFor();
 assert.equal(await page.title(), 'Cybernetic-Physics — Research Workbench · Preview v7');
 const typography = await page.evaluate(async () => {
  await document.fonts.ready;
  return { faces: [...document.fonts].map(font => ({ family: font.family.replace(/["']/g, ''), status: font.status })), body: getComputedStyle(document.body).fontFamily, heading: getComputedStyle(document.querySelector('h1')).fontFamily, label: getComputedStyle(document.querySelector('.preview-eyebrow')).fontFamily };
 });
 for (const family of ['Tomorrow', 'IBM Plex Sans', 'Kode Mono']) assert.ok(typography.faces.some(face => face.family === family && face.status === 'loaded'), `${family} did not load offline`);
 assert.match(typography.body, /IBM Plex Sans/);
 assert.match(typography.heading, /Tomorrow/);
 assert.match(typography.label, /Kode Mono/);
 assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor), 'rgb(0, 0, 0)');
 assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()), '#4f8d7d');
 const darkPrimaryContrast = await primaryHoverContrast();
 await page.getByText('Typography licenses', { exact: true }).click();
 assert.match(await page.locator('.preview-font-notices pre').innerText(), /SIL OPEN FONT LICENSE/);
 await page.getByText('Typography licenses', { exact: true }).click();
 const expandedWidth = (await page.getByRole('complementary', { name: 'Workspace sidebar' }).boundingBox()).width;
 const topBox = await top.boundingBox();
 assert.equal(topBox.x, 0);
 assert.ok(Math.abs(topBox.width - await page.evaluate(() => document.documentElement.clientWidth)) < 2);
 await shot('environment-dark');

 await page.getByLabel('Scenario prompt', { exact: true }).fill('Droid moves the banana onto the large plate.');
 await sidebar.getByRole('button', { name: 'Collapse left sidebar', exact: true }).click();
 assert.equal(await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).getAttribute('aria-expanded'), 'false');
 assert.ok((await page.getByRole('complementary', { name: 'Workspace sidebar' }).boundingBox()).width < expandedWidth);
 await shot('v5-sidebar-collapsed');
 const panelBox = await sidebar.boundingBox();
 const toggleBox = await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).boundingBox();
 assert.ok(toggleBox.x >= panelBox.x && toggleBox.x + toggleBox.width <= panelBox.x + panelBox.width && toggleBox.y >= panelBox.y, 'Collapse control must be physically inside the sidebar');
 await nav.getByRole('button', { name: 'Library', exact: true }).click();
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 assert.equal(await page.getByLabel('Scenario prompt', { exact: true }).inputValue(), 'Droid moves the banana onto the large plate.');
 await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).click();
 await nav.getByRole('button', { name: 'Environment', exact: true }).focus();
 await page.keyboard.press('Escape');
 assert.equal(await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).evaluate(element => element === document.activeElement), true);
 await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).click();
 for (const [label, title, screenshot] of [['Login', 'Login preview', 'v5-login'], ['Sign up', 'Sign up preview', 'v5-signup']]) {
  await top.getByRole('button', { name: label, exact: true }).click();
  const account = page.getByRole('dialog', { name: title, exact: true });
  await account.getByText(/No credentials are accepted/).waitFor();
  assert.equal(await account.locator('input:not(:disabled), form').count(), 0);
  assert.ok((await account.locator('input').evaluateAll(inputs => inputs.map(input => input.value))).every(value => value === ''));
  await shot(screenshot);
  await page.keyboard.press('Escape');
  assert.equal(await account.count(), 0);
 }
 await page.getByRole('button', { name: 'Preview generation request', exact: true }).click();
 await page.getByTestId('request-summary').getByText('No base document', { exact: true }).waitFor();
 await page.getByRole('button', { name: 'Show example candidate', exact: true }).click();
 await page.getByRole('button', { name: 'Review example candidate', exact: true }).click();
 await page.getByRole('button', { name: 'Apply example to draft', exact: true }).click();
 assert.match(await page.getByLabel('Draft YAML', { exact: true }).inputValue(), /example-a2/);
 await page.getByRole('button', { name: 'Review version save', exact: true }).click();
 await page.getByRole('button', { name: 'Create local example version', exact: true }).click();
 assert.match(await page.getByTestId('selection-context').innerText(), /example-local-1/);
 await shot('candidate-and-local-version');
 for (const [name, id] of [['Library','library'],['Assets & scene','visualizer'],['Build & evaluate','build'],['Improve','improve'],['Experiments','experiments'],['Runs & evidence','runs'],['Neo4j query','neo4j'],['Research graph','graph'],['Jobs & diagnostics','jobs'],['Settings & readiness','settings'],['Coverage & reference','coverage']]) {
  await nav.getByRole('button', { name, exact: true }).click();
  await page.getByRole('heading', { name, exact: true, level: 1 }).waitFor();
  assert.equal(await page.locator('#preview-main > section:visible').count(), 1);
  await shot(id);
 }
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 assert.match(await page.getByLabel('Draft YAML', { exact: true }).inputValue(), /example-a2/);
 // Historical pixels are decoded and checked, never re-rendered or relabelled.
 const beforeActivity = await page.getByLabel('Draft YAML', { exact: true }).inputValue();
 await page.getByRole('button', { name: 'Activity examples', exact: true }).click();
 const activity = page.getByRole('region', { name: 'Activity preview', exact: true });
 await activity.getByRole('button', { name: 'Show example jobs', exact: true }).click();
 await shot('v7-activity');
 await activity.getByRole('button', { name: 'Inspect example-blocked', exact: true }).click();
 const linkedJob = page.getByRole('region', { name: 'Exact example job inspector', exact: true });
 assert.match(await linkedJob.innerText(), /example-blocked/);
 await page.getByLabel('Snapshot example state', { exact: true }).selectOption('unavailable');
 await page.getByRole('button', { name: 'Activity examples', exact: true }).click();
 await activity.getByRole('button', { name: 'Inspect example-blocked', exact: true }).click();
 await page.getByLabel('Requested job navigation', { exact: true }).waitFor();
 assert.match(await page.getByLabel('Requested job navigation', { exact: true }).innerText(), /details unavailable/);
 assert.equal(await linkedJob.count(), 0);
 await page.getByLabel('Snapshot example state', { exact: true }).selectOption('available');
 await page.getByRole('button', { name: 'Activity examples', exact: true }).click();
 await activity.getByRole('button', { name: 'Open independent research examples', exact: true }).click();
 await page.getByRole('heading', { name: 'Runs & evidence', exact: true, level: 1 }).waitFor();
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 assert.equal(await page.getByLabel('Draft YAML', { exact: true }).inputValue(), beforeActivity);
 await nav.getByRole('button', { name: 'Assets & scene', exact: true }).click();
 const visualizer = page.getByRole('region', { name: 'Assets & scene workspace', exact: true });
 async function checkHistoricalImage(expected) {
  const image = visualizer.locator('.preview-visualizer-image img');
  await image.evaluate(async element => { await element.decode(); });
  assert.deepEqual(await image.evaluate(element => [element.naturalWidth, element.naturalHeight]), [512, 512]);
  const url = await image.getAttribute('src');
  assert.ok(url.startsWith('data:image/png;base64,'));
  const sha = createHash('sha256').update(Buffer.from(url.split(',')[1], 'base64')).digest('hex');
  assert.equal(sha, expected);
  if (!historicalImages.includes(sha)) historicalImages.push(sha);
 }
 await checkHistoricalImage('a08b8cd388464b42449913e4b7d39063c412e2a46340459e8b3520b23cbc7a87');
 await shot('v6-asset-table');
 await visualizer.getByLabel('Saved subject', { exact: true }).selectOption('Rubik’s cube');
 await checkHistoricalImage('c6271ce16e4e7329b69e32494dff8503d245827fe45d0f7027c8f1703f8e66b0');
 await shot('v6-asset-cube');
 await visualizer.getByLabel('Saved camera', { exact: true }).selectOption('front');
 assert.equal(await visualizer.locator('.preview-visualizer-image img').count(), 0);
 await visualizer.getByText(/No saved front view/).waitFor();
 await visualizer.getByLabel('Saved camera', { exact: true }).selectOption('isometric');
 await visualizer.getByRole('tab', { name: 'Scene', exact: true }).click();
 await checkHistoricalImage('5175eb085aeb303de899a3b127ab780e05c5264f4d08bab7c9fbd301aa384999');
 await shot('v6-scene');
 await visualizer.getByRole('button', { name: 'Zoom historical image', exact: true }).click();
 const imageZoom = page.getByRole('dialog', { name: 'Historical image zoom', exact: true });
 await imageZoom.locator('img').evaluate(async element => { await element.decode(); });
 await shot('v6-scene-zoom');
 await page.keyboard.press('Escape');
 assert.equal(await imageZoom.count(), 0);
 assert.equal(await visualizer.getByRole('button', { name: 'Zoom historical image', exact: true }).evaluate(element => element === document.activeElement), true);
 await visualizer.locator('.preview-visualizer-image img').dispatchEvent('error');
 await visualizer.getByRole('button', { name: 'Retry saved image', exact: true }).click();
 await checkHistoricalImage('5175eb085aeb303de899a3b127ab780e05c5264f4d08bab7c9fbd301aa384999');
 await visualizer.getByLabel('I understand this render plan is local only', { exact: true }).check();
 await visualizer.getByRole('button', { name: 'Review render request locally', exact: true }).click();
 const renderPlan = await visualizer.getByTestId('visualizer-render-review').innerText();
 await visualizer.getByLabel('Planned camera', { exact: true }).selectOption('front');
 await visualizer.getByLabel('Planned camera', { exact: true }).selectOption('isometric');
 assert.equal(await visualizer.getByTestId('visualizer-render-review').innerText(), renderPlan);
 await visualizer.getByText(/Render review is stale/).waitFor();
 assert.equal(await visualizer.getByLabel('I understand this render plan is local only', { exact: true }).isChecked(), false);
 await visualizer.getByRole('tab', { name: 'Live RTX exploration', exact: true }).click();
 await visualizer.getByLabel('Interaction intent', { exact: true }).selectOption('picking');
 await visualizer.getByLabel('I understand this is requirements review, not connection consent', { exact: true }).check();
 await visualizer.getByRole('button', { name: 'Review live requirements locally', exact: true }).click();
 const livePlan = await visualizer.getByTestId('visualizer-live-review').innerText();
 assert.equal(await visualizer.getByRole('button', { name: 'Connect', exact: true }).isDisabled(), true);
 await shot('v6-live-rtx-exploration');
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 await page.getByLabel('Draft YAML', { exact: true }).waitFor();
 const visualizerDraft = await page.getByLabel('Draft YAML', { exact: true }).inputValue();
 await page.getByLabel('Draft YAML', { exact: true }).fill(visualizerDraft + '\n# local visualization edit');
 await page.getByLabel('Draft YAML', { exact: true }).fill(visualizerDraft);
 await nav.getByRole('button', { name: 'Assets & scene', exact: true }).click();
 assert.equal(await visualizer.getByTestId('visualizer-live-review').innerText(), livePlan);
 await visualizer.getByText(/Live requirements review is stale/).waitFor();
 assert.equal(await visualizer.getByLabel('I understand this is requirements review, not connection consent', { exact: true }).isChecked(), false);
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 // Restored query and operational workspaces are independent of editor inputs.
 await nav.getByRole('button', { name: 'Neo4j query', exact: true }).click();
 const queryWorkspace = page.getByRole('region', { name: 'Neo4j query workspace', exact: true });
 assert.equal(await page.getByRole('button', { name: 'Review version save', exact: true }).count(), 0);
 assert.equal(await queryWorkspace.getByRole('combobox', { name: 'Publication operation', exact: true }).count(), 0);
 await queryWorkspace.getByLabel('Parameters (JSON object)', { exact: true }).fill(' { "name": "Example tabletop" } ');
 assert.equal(await queryWorkspace.getByRole('button', { name: 'Load example fixture', exact: true }).isDisabled(), false);
 await queryWorkspace.getByRole('button', { name: 'Review query locally', exact: true }).click();
 const frozenQuery = await queryWorkspace.getByTestId('frozen-query-review').innerText();
 assert.equal(await queryWorkspace.getByRole('table', { name: 'Example Neo4j rows', exact: true }).count(), 0);
 await queryWorkspace.getByRole('button', { name: 'Load example fixture', exact: true }).click();
 await shot('v5-query-table');
 await queryWorkspace.getByRole('button', { name: 'Graph', exact: true }).click();
 await queryWorkspace.getByRole('button', { name: 'Inspect Example G1', exact: true }).focus();
 await page.keyboard.press('Enter');
 await queryWorkspace.getByRole('region', { name: 'Example node inspector', exact: true }).getByText(/example-robot/).waitFor();
 await shot('v5-query-graph');
 await queryWorkspace.getByLabel('Parameters (JSON object)', { exact: true }).fill('{"name":"Custom"}');
 assert.equal(await queryWorkspace.getByRole('button', { name: 'Load example fixture', exact: true }).isDisabled(), true);
 await queryWorkspace.getByText(/Custom-query results unavailable/).waitFor();
 await queryWorkspace.getByText(/Fixture is stale/).waitFor();
 assert.equal(await queryWorkspace.getByTestId('frozen-query-review').innerText(), frozenQuery);
 await shot('v5-query-stale');
 await queryWorkspace.getByLabel('Parameters (JSON object)', { exact: true }).fill('{"value":[1e999]}');
 await queryWorkspace.getByRole('alert').getByText(/finite numbers/).waitFor();
 await queryWorkspace.getByText(/Fixture is stale/).waitFor();
 assert.equal(await queryWorkspace.getByTestId('frozen-query-review').innerText(), frozenQuery);
 for (const fixture of ['empty', 'error', 'truncated']) {
  await queryWorkspace.getByLabel('Query example', { exact: true }).selectOption(fixture);
  await queryWorkspace.getByRole('button', { name: 'Load example fixture', exact: true }).click();
  await queryWorkspace.getByText(new RegExp(`${fixture[0].toUpperCase()}${fixture.slice(1)} fixture`)).waitFor();
 }
 await queryWorkspace.getByLabel('Query example', { exact: true }).selectOption('relationships');
 await queryWorkspace.getByRole('button', { name: 'Load example fixture', exact: true }).click();
 await nav.getByRole('button', { name: 'Jobs & diagnostics', exact: true }).click();
 const jobsWorkspace = page.getByRole('region', { name: 'Jobs & diagnostics workspace', exact: true });
 await jobsWorkspace.getByLabel('Filter jobs', { exact: true }).selectOption('active');
 assert.equal(await jobsWorkspace.getByRole('button', { name: 'Inspect example-succeeded', exact: true }).count(), 0);
 await jobsWorkspace.getByRole('button', { name: 'Inspect example-blocked', exact: true }).click();
 await jobsWorkspace.getByLabel('Authorization example', { exact: true }).selectOption('available');
 await jobsWorkspace.getByRole('button', { name: 'Review authorization renewal', exact: true }).click();
 await jobsWorkspace.getByLabel('Confirm this exact example job action; nothing will be sent', { exact: true }).check();
 await jobsWorkspace.getByRole('button', { name: 'Freeze job action review', exact: true }).click();
 const frozenJobAction = await jobsWorkspace.getByLabel('Frozen job action review', { exact: true }).innerText();
 await jobsWorkspace.getByRole('button', { name: 'Inspect example-queued', exact: true }).click();
 assert.equal(await jobsWorkspace.getByLabel('Frozen job action review', { exact: true }).innerText(), frozenJobAction);
 await jobsWorkspace.getByText(/not the selected example-queued/).waitFor();
 await shot('v5-job-exact-target');
 await jobsWorkspace.getByRole('button', { name: 'Close frozen job action review', exact: true }).click();
 await jobsWorkspace.getByRole('button', { name: 'Review cancellation', exact: true }).click();
 await jobsWorkspace.getByLabel('Confirm this exact example job action; nothing will be sent', { exact: true }).check();
 await jobsWorkspace.getByRole('button', { name: 'Inspect example-running', exact: true }).click();
 await jobsWorkspace.getByRole('button', { name: 'Inspect example-queued', exact: true }).click();
 assert.equal(await jobsWorkspace.getByLabel('Confirm this exact example job action; nothing will be sent', { exact: true }).count(), 0);
 await jobsWorkspace.getByRole('tab', { name: 'Developer diagnostics', exact: true }).click();
 assert.equal(await jobsWorkspace.getByRole('button', { name: 'Review diagnostic request', exact: true }).isDisabled(), true);
 await jobsWorkspace.getByLabel('Diagnostic capability example', { exact: true }).selectOption('available');
 await jobsWorkspace.getByLabel('Consent to local diagnostic review only', { exact: true }).check();
 await jobsWorkspace.getByLabel('Steps', { exact: true }).fill('11');
 assert.equal(await jobsWorkspace.getByRole('button', { name: 'Review diagnostic request', exact: true }).isDisabled(), true);
 await jobsWorkspace.getByLabel('Steps', { exact: true }).fill('4');
 await jobsWorkspace.getByLabel('Delay per step (s)', { exact: true }).fill('0.5');
 await jobsWorkspace.getByRole('button', { name: 'Review diagnostic request', exact: true }).click();
 await jobsWorkspace.getByRole('button', { name: 'Review retained retry', exact: true }).click();
 const frozenDiagnostic = await jobsWorkspace.getByLabel('Frozen diagnostic request', { exact: true }).innerText();
 assert.equal(await jobsWorkspace.getByLabel('Frozen retry review', { exact: true }).innerText(), frozenDiagnostic);
 await shot('v5-diagnostic-retained-request');
 await jobsWorkspace.getByRole('button', { name: 'Review queue resume', exact: true }).click();
 await jobsWorkspace.getByLabel('Confirm review of the entire example queue; do not resume it', { exact: true }).check();
 await jobsWorkspace.getByRole('button', { name: 'Freeze queue resume review', exact: true }).click();
 const queueReview = JSON.parse(await jobsWorkspace.getByLabel('Frozen queue resume review', { exact: true }).innerText());
 assert.ok(queueReview.exampleOnly && queueReview.targets.every(target => target.status === 'queued'));
 await shot('v5-queue-resume-review');
 await nav.getByRole('button', { name: 'Neo4j query', exact: true }).click();
 assert.equal(await queryWorkspace.getByTestId('frozen-query-review').innerText(), frozenQuery);
 await nav.getByRole('button', { name: 'Jobs & diagnostics', exact: true }).click();
 assert.equal(await jobsWorkspace.getByLabel('Frozen diagnostic request', { exact: true }).innerText(), frozenDiagnostic);
 assert.equal(await jobsWorkspace.getByLabel('Frozen retry review', { exact: true }).innerText(), frozenDiagnostic);
 assert.deepEqual(JSON.parse(await jobsWorkspace.getByLabel('Frozen queue resume review', { exact: true }).innerText()), queueReview);
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 assert.match(await page.getByLabel('Draft YAML', { exact: true }).inputValue(), /example-a2/);
 // The messy-history case: one family row, explicit numeric version selection.
 await nav.getByRole('button', { name: 'Library', exact: true }).click();
 await page.getByLabel('Search example library', { exact: true }).fill('C1');
 assert.equal(await page.getByRole('table', { name: 'Example document families' }).locator('tbody tr').count(), 1);
 await page.getByRole('button', { name: 'Inspect C1 · G1 tabletop', exact: true }).click();
 const versions = page.getByLabel('Inspect version', { exact: true });
 assert.deepEqual(await versions.locator('option').evaluateAll(options => options.map(option => option.textContent?.split(' · ')[0])), Array.from({ length: 12 }, (_, i) => `v${i + 1}`));
 await versions.selectOption('example-c1-g1-tabletop-v12');
 assert.match(await page.getByTestId('selection-context').innerText(), /example-local-1/);
 await shot('c1-version-inspector');
 await page.getByRole('button', { name: 'Open environment', exact: true }).click();
 await page.getByRole('dialog', { name: 'Replace unsaved workspace inputs?' }).getByRole('button', { name: 'Keep current draft', exact: true }).click();
 assert.match(await page.getByTestId('selection-context').innerText(), /example-local-1/);
 await page.getByRole('button', { name: 'Open environment', exact: true }).click();
 await page.getByRole('button', { name: 'Discard edits and continue', exact: true }).click();
 assert.match(await page.getByTestId('selection-context').innerText(), /example-c1-g1-tabletop-v12/);
 await shot('c1-opened');
 await page.getByLabel('Refine selected version', { exact: true }).check();
 await page.getByLabel('Refinement feedback', { exact: true }).fill('Example refinement feedback');
 await nav.getByRole('button', { name: 'Library', exact: true }).click();
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 assert.equal(await page.getByLabel('Refinement feedback', { exact: true }).inputValue(), 'Example refinement feedback');
 await page.getByLabel('Environment version', { exact: true }).selectOption('example-c1-g1-tabletop-v11');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 await page.getByRole('button', { name: 'Discard edits and continue', exact: true }).click();
 await page.getByLabel('Refine selected version', { exact: true }).check();
 assert.equal(await page.getByLabel('Refinement feedback', { exact: true }).inputValue(), '');
 await page.getByLabel('Refinement feedback', { exact: true }).fill('Reset this new source-bound feedback');
 await page.getByRole('button', { name: 'Preview generation request', exact: true }).click();
 assert.match(await page.getByTestId('request-summary').innerText(), /example-c1-g1-tabletop-v11/);
 await shot('refinement-review');
 await page.getByRole('button', { name: 'Start new draft', exact: true }).click();
 await page.getByRole('button', { name: 'Discard edits and continue', exact: true }).click();
 assert.equal(await page.getByLabel('New environment', { exact: true }).isChecked(), true);
 assert.equal(await page.getByLabel('Scenario prompt', { exact: true }).inputValue(), '');
 assert.equal(await page.getByTestId('request-summary').count(), 0);
 await shot('reset-to-new');
 await page.getByLabel('Environment family', { exact: true }).selectOption('example-c1-g1-tabletop');
 await page.getByLabel('Environment version', { exact: true }).selectOption('example-c1-g1-tabletop-v12');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 await nav.getByRole('button', { name: 'Build & evaluate', exact: true }).click();
 const build = page.getByRole('region', { name: 'Build & evaluate workspace', exact: true });
 assert.match(await build.locator('[aria-label="Bound workflow source"]').innerText(), /example-local-1/);
 await build.getByLabel('Keep form options for the selected saved version; review all target-specific consent again', { exact: true }).check();
 await build.getByRole('button', { name: 'Rebind form to selected version', exact: true }).click();
 assert.match(await build.locator('[aria-label="Bound workflow source"]').innerText(), /example-c1-g1-tabletop-v12/);
 await build.getByLabel('Build purpose', { exact: true }).selectOption('evaluate');
 await build.getByRole('button', { name: 'Preview request', exact: true }).click();
 assert.match(await build.getByRole('alert').innerText(), /checkpoint/);
 await build.getByLabel('Checkpoint or server identity', { exact: true }).fill('example-checkpoint');
 await build.getByRole('button', { name: 'Preview request', exact: true }).click();
 assert.match(await build.getByTestId('frozen-request').innerText(), /example-c1-g1-tabletop-v12/);
 await shot('evaluation-confirmation');
 await nav.getByRole('button', { name: 'Research graph', exact: true }).click();
 const graph = page.getByRole('region', { name: 'Research graph workspace', exact: true });
 await graph.getByLabel('Keep form options for the selected saved version; review all target-specific consent again', { exact: true }).check();
 await graph.getByRole('button', { name: 'Rebind form to selected version', exact: true }).click();
 await graph.getByLabel('Graph view', { exact: true }).selectOption('publication');
 await graph.getByLabel('Publication operation', { exact: true }).selectOption('publish');
 await graph.getByLabel('Publication example state', { exact: true }).selectOption('unknown');
 assert.equal(await graph.getByRole('button', { name: 'Preview request', exact: true }).isDisabled(), true);
 await graph.getByLabel('Publication operation', { exact: true }).selectOption('observe');
 await graph.getByRole('button', { name: 'Preview request', exact: true }).click();
 assert.match(await graph.getByTestId('frozen-request').innerText(), /observe/);
 await shot('unknown-publication-observation');
 await nav.getByRole('button', { name: 'Runs & evidence', exact: true }).click();
 const runs = page.getByRole('region', { name: 'Runs & evidence workspace', exact: true });
 await runs.getByText('Compare exact run identities', { exact: true }).click();
 await runs.getByLabel('Comparison example run', { exact: true }).selectOption('example-unknown');
 await runs.getByRole('button', { name: 'Preview request', exact: true }).click();
 const frozenComparison = await runs.getByTestId('frozen-request').innerText();
 await runs.getByLabel('Selected example run', { exact: true }).selectOption('example-unknown');
 assert.equal(await runs.getByLabel('Comparison example run', { exact: true }).inputValue(), 'none');
 assert.equal(await runs.getByTestId('frozen-request').innerText(), frozenComparison);
 await runs.getByRole('button', { name: 'Back to form', exact: true }).click();
 await runs.getByRole('button', { name: 'Preview request', exact: true }).click();
 const newComparison = JSON.parse(await runs.getByTestId('frozen-request').innerText());
 assert.equal(newComparison.options.selectedRun, 'example-unknown');
 assert.equal(newComparison.options.compare, 'none');
 await runs.getByRole('button', { name: 'Back to form', exact: true }).click();
 await runs.getByLabel('Selected example run', { exact: true }).selectOption('example-zero-episodes');
 await runs.getByText('Success rate: unavailable (null)', { exact: true }).waitFor();
 await shot('zero-episode-evidence');
 await nav.getByRole('button', { name: 'Improve', exact: true }).click();
 const improve = page.getByRole('region', { name: 'Improve workspace', exact: true });
 await improve.getByLabel('Keep form options for the selected saved version; review all target-specific consent again', { exact: true }).check();
 await improve.getByRole('button', { name: 'Rebind form to selected version', exact: true }).click();
 await improve.getByLabel('Failed evidence', { exact: true }).selectOption('example-c1-failed-run');
 assert.match(await improve.getByRole('status', { name: 'Repair evidence status' }).innerText(), /mismatch/);
 assert.equal(await improve.getByRole('button', { name: 'Preview request', exact: true }).isDisabled(), true);
 await shot('repair-evidence-mismatch');
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 await page.getByLabel('Environment version', { exact: true }).selectOption('example-c1-g1-tabletop-v1');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 await nav.getByRole('button', { name: 'Improve', exact: true }).click();
 assert.match(await improve.locator('[aria-label="Bound workflow source"]').innerText(), /example-c1-g1-tabletop-v12/);
 await improve.getByLabel('Keep form options for the selected saved version; review all target-specific consent again', { exact: true }).check();
 await improve.getByRole('button', { name: 'Rebind form to selected version', exact: true }).click();
 await improve.getByLabel('Repair policy identity', { exact: true }).selectOption('example-c1-gr00t');
 await improve.getByLabel('Repair policy configuration', { exact: true }).selectOption('example-c1-policy-config-v1');
 await improve.getByLabel('Repair feedback', { exact: true }).fill('Inspect this example constraint without accepting changes.');
 await improve.getByRole('button', { name: 'Preview request', exact: true }).click();
 assert.match(await improve.getByTestId('frozen-request').innerText(), /example-c1-g1-tabletop-v1/);
 await shot('repair-matched-evidence');
 await improve.getByRole('button', { name: 'Back to form', exact: true }).click();
 await improve.getByLabel('Improvement example state', { exact: true }).selectOption('candidate');
 const proposalAcceptance = improve.getByLabel('Accept example proposal locally (no editor change)', { exact: true });
 await proposalAcceptance.check();
 assert.equal(await proposalAcceptance.isChecked(), true);
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 await page.getByLabel('Environment version', { exact: true }).selectOption('example-c1-g1-tabletop-v2');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 await nav.getByRole('button', { name: 'Improve', exact: true }).click();
 assert.equal(await proposalAcceptance.isChecked(), true); // Still explicitly bound to v1.
 await improve.getByLabel('Keep form options for the selected saved version; review all target-specific consent again', { exact: true }).check();
 await improve.getByRole('button', { name: 'Rebind form to selected version', exact: true }).click();
 assert.equal(await proposalAcceptance.isChecked(), false);
 assert.equal(await proposalAcceptance.isDisabled(), true);
 await shot('proposal-rebind-clears-acceptance');
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 await page.getByLabel('Environment version', { exact: true }).selectOption('example-c1-g1-tabletop-v1');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 await nav.getByRole('button', { name: 'Improve', exact: true }).click();
 await improve.getByLabel('Keep form options for the selected saved version; review all target-specific consent again', { exact: true }).check();
 await improve.getByRole('button', { name: 'Rebind form to selected version', exact: true }).click();
 assert.equal(await proposalAcceptance.isChecked(), false);
 await improve.getByLabel('Improvement workflow', { exact: true }).selectOption('assistance');
 await improve.getByLabel('Assistance mode', { exact: true }).selectOption('offset');
 await improve.getByLabel('Consent to privileged-state example review', { exact: true }).check();
 await improve.getByText('Advanced assistance, trial & trace details', { exact: true }).click();
 await improve.getByLabel('Maximum offset (mm)', { exact: true }).fill('6');
 await improve.getByLabel('Maximum offset (mm)', { exact: true }).fill('5');
 assert.equal(await improve.getByLabel('Consent to privileged-state example review', { exact: true }).isChecked(), false);
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 // V7: actual local authored edit, recovery, download and exact-version review.
 await page.getByLabel('Environment family', { exact: true }).selectOption('example-inspection');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 const discardInputs = page.getByRole('button', { name: 'Discard edits and continue', exact: true });
 if (await discardInputs.isVisible()) await discardInputs.click();
 const inspection = page.getByRole('region', { name: 'Inspect and correct workspace', exact: true });
 const specification = page.getByLabel('Draft YAML', { exact: true });
 const inspectionBase = await specification.inputValue();
 assert.equal(JSON.parse(inspectionBase).previewSchema, 'inspect-correct/v1');
 const embeddedViewer = page.getByRole('region', { name: 'Asset and scene visualizer', exact: true });
 await embeddedViewer.getByRole('tab', { name: 'Scene', exact: true }).click();
 await embeddedViewer.locator('img').evaluate(element => element.decode());
 const unchangedHistoricalPixels = await embeddedViewer.locator('.preview-visualizer-image img').getAttribute('src');
 await embeddedViewer.evaluate(element => { element.dataset.v7Retained = 'same-viewer'; });
 await inspection.getByRole('button', { name: 'Select cube', exact: true }).click();
 await shot('v7-inspect-dark');
 const specificationWidth = inspection.getByRole('slider', { name: 'Specification width', exact: true });
 const retainedWidth = await specificationWidth.inputValue();
 await specification.evaluate(element => { element.dataset.v7Retained = 'same-specification'; });
 await specificationWidth.evaluate(element => { element.dataset.v7Retained = 'same-width-control'; });
 for (const width of [1050, 1200]) {
  await page.setViewportSize({ width, height: 1080 });
  assert.equal(await specificationWidth.count(), 0, `Specification width must not be advertised at ${width}px when the grid ignores it`);
  assert.equal(await inspection.locator('.inspect-spec-width input').count(), 1, 'Responsive layout must retain the width control DOM');
  assert.equal(await specification.inputValue(), inspectionBase);
  assert.equal(await embeddedViewer.getAttribute('data-v7-retained'), 'same-viewer');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `Inspection workspace overflows horizontally at ${width}px`);
  await shot(`v7-inspect-${width}px`);
 }
 await page.setViewportSize({ width: 1440, height: 1080 });
 assert.equal(await specificationWidth.isVisible(), true);
 assert.equal(await specificationWidth.isEnabled(), true);
 assert.equal(await specificationWidth.inputValue(), retainedWidth);
 assert.equal(await specificationWidth.getAttribute('data-v7-retained'), 'same-width-control');
 assert.equal(await specification.getAttribute('data-v7-retained'), 'same-specification');
 const widthBefore = (await inspection.locator('.inspect-specification').boundingBox()).width;
 await inspection.getByRole('slider', { name: 'Specification width', exact: true }).focus();
 await page.keyboard.press('End');
 assert.ok((await inspection.locator('.inspect-specification').boundingBox()).width > widthBefore);
 assert.equal(await specification.inputValue(), inspectionBase);
 await inspection.getByRole('button', { name: 'Hide specification', exact: true }).click();
 assert.equal(await specification.isVisible(), false);
 await inspection.getByRole('button', { name: 'Show specification', exact: true }).click();
 await inspection.getByRole('button', { name: 'Hide inspector', exact: true }).click();
 await inspection.getByRole('button', { name: 'Expand viewport', exact: true }).click();
 assert.equal(await embeddedViewer.getAttribute('data-v7-retained'), 'same-viewer');
 await shot('v7-expanded-viewport');
 await inspection.getByRole('button', { name: 'Return to editor', exact: true }).click();
 assert.equal(await inspection.getByRole('complementary', { name: 'Authored asset inspector', exact: true }).count(), 0);
 await inspection.getByRole('button', { name: 'Show inspector', exact: true }).click();
 assert.equal(await inspection.getByRole('button', { name: 'Select cube', exact: true }).getAttribute('aria-pressed'), 'true');
 await inspection.getByRole('slider', { name: 'Specification width', exact: true }).focus();
 await page.keyboard.press('Home');
 await inspection.getByRole('button', { name: 'Keep recovery copy', exact: true }).click();
 await inspection.getByLabel('Proposed value', { exact: true }).fill('0.5');
 await inspection.getByRole('button', { name: 'Review pose change', exact: true }).click();
 const frozenPose = inspection.getByRole('region', { name: 'Frozen pose review', exact: true });
 const poseDiff = await frozenPose.locator('pre').innerText();
 await inspection.getByLabel('I consent to replace the draft with this reviewed pose change', { exact: true }).check();
 await inspection.getByLabel('Proposed value', { exact: true }).fill('0.6');
 await inspection.getByLabel('Proposed value', { exact: true }).fill('0.5');
 assert.equal(await frozenPose.locator('pre').innerText(), poseDiff);
 assert.equal(await inspection.getByRole('button', { name: 'Apply reviewed pose change', exact: true }).isDisabled(), true);
 await inspection.getByRole('button', { name: 'Clear pose review', exact: true }).click();
 await inspection.getByRole('button', { name: 'Review pose change', exact: true }).click();
 await shot('v7-pose-review');
 assert.equal(await specification.inputValue(), inspectionBase);
 await inspection.getByLabel('I consent to replace the draft with this reviewed pose change', { exact: true }).check();
 await inspection.getByRole('button', { name: 'Apply reviewed pose change', exact: true }).click();
 const editedInspection = await specification.inputValue();
 assert.equal(JSON.parse(editedInspection).assets[1].pose.position[0], 0.5);
 assert.equal(await embeddedViewer.locator('.preview-visualizer-image img').getAttribute('src'), unchangedHistoricalPixels);
 const downloaded = page.waitForEvent('download');
 await inspection.getByRole('button', { name: 'Download raw draft', exact: true }).click();
 const download = await downloaded;
 assert.equal(download.suggestedFilename(), 'inspection-draft.yaml');
 await download.saveAs(`${output}/v7-inspection-draft.yaml`);
 assert.equal(await readFile(`${output}/v7-inspection-draft.yaml`, 'utf8'), editedInspection);
 await inspection.getByRole('button', { name: 'Review recovery copy', exact: true }).click();
 await inspection.getByLabel('I consent to replace the current draft with this recovery copy', { exact: true }).check();
 await specification.fill(editedInspection + '\n');
 await specification.fill(editedInspection);
 assert.equal(await inspection.getByRole('button', { name: 'Restore reviewed recovery copy', exact: true }).isDisabled(), true);
 await inspection.getByRole('button', { name: 'Review recovery copy', exact: true }).click();
 await inspection.getByLabel('I consent to replace the current draft with this recovery copy', { exact: true }).check();
 await shot('v7-recovery-review');
 await inspection.getByRole('button', { name: 'Restore reviewed recovery copy', exact: true }).click();
 assert.equal(await specification.inputValue(), inspectionBase);
 await inspection.getByRole('button', { name: 'Clear pose review', exact: true }).click();
 const invalidScale = JSON.parse(inspectionBase); invalidScale.assets[1].scale[0] = 0;
 await specification.fill(JSON.stringify(invalidScale, null, 2));
 await inspection.getByRole('button', { name: 'Inspect finding: assets[1].scale', exact: true }).click();
 assert.equal(await specification.evaluate(element => document.activeElement === element), true);
 assert.match(await specification.evaluate(element => element.value.slice(element.selectionStart, element.selectionEnd)), /scale/);
 await shot('v7-actionable-validation');
 await specification.fill(inspectionBase);
 await inspection.getByRole('button', { name: 'Keep recovery copy', exact: true }).click();
 await nav.getByRole('button', { name: 'Library', exact: true }).click();
 const versionLibrary = page.getByRole('region', { name: 'Library workspace', exact: true });
 await versionLibrary.getByLabel('Search example library', { exact: true }).fill('Synthetic inspection');
 await versionLibrary.getByRole('button', { name: 'Inspect Synthetic inspection lab', exact: true }).click();
 await versionLibrary.getByRole('button', { name: 'Pin inspected version', exact: true }).click();
 assert.match(await versionLibrary.getByRole('region', { name: 'Local pins', exact: true }).innerText(), /example-inspection-v1/);
 assert.match(await versionLibrary.getByRole('region', { name: 'Recent opens', exact: true }).innerText(), /example-inspection-v1/);
 await versionLibrary.getByLabel('Compare with version', { exact: true }).selectOption('example-inspection-v2');
 await versionLibrary.getByRole('button', { name: 'Freeze version comparison', exact: true }).click();
 const versionComparison = versionLibrary.getByRole('region', { name: 'Frozen version comparison', exact: true });
 const frozenVersionSources = await versionComparison.locator('pre').allTextContents();
 await shot('v7-library-comparison');
 await versionLibrary.getByLabel('Inspect version', { exact: true }).selectOption('example-inspection-v2');
 assert.equal(await versionLibrary.getByLabel('Compare with version', { exact: true }).inputValue(), '');
 assert.deepEqual(await versionComparison.locator('pre').allTextContents(), frozenVersionSources);
 await versionLibrary.getByRole('button', { name: 'Clear frozen comparison', exact: true }).click();
 assert.equal(await versionLibrary.getByRole('button', { name: 'Freeze version comparison', exact: true }).isDisabled(), true);
 await versionLibrary.getByRole('button', { name: 'Open environment', exact: true }).click();
 await inspection.getByRole('button', { name: 'Review recovery copy', exact: true }).waitFor();
 assert.equal(await inspection.getByRole('button', { name: 'Review recovery copy', exact: true }).isDisabled(), true);
 await page.getByLabel('Environment version', { exact: true }).selectOption('example-inspection-v1');
 await page.getByRole('button', { name: 'Open selected version', exact: true }).click();
 assert.equal(await inspection.getByRole('button', { name: 'Review recovery copy', exact: true }).isDisabled(), true);
 await inspection.getByRole('button', { name: 'Discard recovery copy', exact: true }).click();
 assert.equal(await embeddedViewer.getAttribute('data-v7-retained'), 'same-viewer');
 const retainedYaml = await specification.inputValue();
 await themeSwitch.focus();
 await page.keyboard.press('Space');
 assert.equal(await themeSwitch.getAttribute('aria-checked'), 'false');
 await page.keyboard.press('Enter');
 assert.equal(await themeSwitch.getAttribute('aria-checked'), 'true');
 await themeSwitch.click();
 assert.equal(await themeSwitch.getAttribute('aria-checked'), 'false');
 assert.equal(await page.getByLabel('Draft YAML', { exact: true }).inputValue(), retainedYaml);
 assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor), 'rgb(255, 255, 255)');
 assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()), '#30666b');
 const lightPrimaryContrast = await primaryHoverContrast();
 await shot('environment-light');
 await page.setViewportSize({ width: 390, height: 844 });
 await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).waitFor();
 await shot('environment-mobile');
 await shot('v7-inspect-mobile');
 assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile page overflows horizontally');
 await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).click();
 await shot('v5-mobile-sidebar-expanded');
 assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Expanded mobile sidebar overflows');
 await nav.getByRole('button', { name: 'Library', exact: true }).click();
 assert.equal(await sidebar.getByRole('button', { name: 'Expand left sidebar', exact: true }).getAttribute('aria-expanded'), 'false');
 await nav.getByRole('button', { name: 'Environment', exact: true }).click();
 await top.getByRole('button', { name: 'Login', exact: true }).click();
 await shot('v5-mobile-login');
 await page.getByRole('button', { name: 'Close account preview', exact: true }).click();
 await page.keyboard.press('Tab');
 assert.notEqual(await page.evaluate(() => document.activeElement?.tagName), 'BODY');

 await page.setViewportSize({ width: 320, height: 740 });
 await shot('v5-320px-header');
 assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), '320px page overflows horizontally');
 for (const control of [themeSwitch, top.getByRole('button', { name: 'Login', exact: true }), top.getByRole('button', { name: 'Sign up', exact: true })]) {
  const box = await control.boundingBox(); const header = await top.boundingBox();
  assert.ok(box.x >= 0 && box.x + box.width <= 320 && box.y >= header.y && box.y + box.height <= header.y + header.height, 'Top account/theme control clipped at 320px');
 }
 for (const [name, screenshot] of [['Neo4j query', 'v5-query-mobile'], ['Jobs & diagnostics', 'v5-jobs-mobile']]) {
  await nav.getByRole('button', { name, exact: true }).click();
  if (name === 'Jobs & diagnostics') await jobsWorkspace.getByRole('tab', { name: 'Job journal', exact: true }).click();
  const scrollRegion = name === 'Neo4j query' ? queryWorkspace.getByRole('region', { name: 'Scrollable example graph', exact: true }) : jobsWorkspace.getByRole('region', { name: 'Scrollable example job journal', exact: true });
  assert.ok(await scrollRegion.evaluate(element => element.scrollWidth > element.clientWidth), 'Narrow data view should scroll instead of shrinking text');
  await scrollRegion.evaluate(element => { element.scrollLeft = element.scrollWidth; });
  assert.ok(await scrollRegion.evaluate(element => element.scrollLeft > 0));
  await scrollRegion.evaluate(element => { element.scrollLeft = 0; });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${name} overflows horizontally at 320px`);
  await shot(screenshot);
 }
 await nav.getByRole('button', { name: 'Assets & scene', exact: true }).click();
 await visualizer.getByRole('tab', { name: 'Scene', exact: true }).click();
 await checkHistoricalImage('5175eb085aeb303de899a3b127ab780e05c5264f4d08bab7c9fbd301aa384999');
 assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile visualizer overflows');
 await shot('v6-visualizer-mobile');
 assert.equal(historicalImages.length, 3);
 assert.deepEqual(denied, [], 'Preview attempted network requests');
 assert.deepEqual(errors, [], 'Browser errors');
 const blockedEffects = await page.evaluate(() => window.__previewBlockedEffects);
 assert.deepEqual(blockedEffects, [], 'Preview attempted storage, worker or RTC operations');
 await writeFile(`${output}/browser-proof.json`, JSON.stringify({ passed: true, previewVersion: 7, blockedEffects, historicalImages, visualization: 'Three embedded historical PNG hashes and decoding checked; missing camera, zoom, injected image-error retry, frozen/stale plans; no renderer/stream connected', restoredWorkspaces: 'Explicit Neo4j query and Jobs & diagnostics; frozen query/fixture provenance, custom-query refusal, exact job target, consent reset, same-ID diagnostic retry and queue review; separate publication and research metrics; zero execution', typography, primaryHoverContrast: { dark: darkPrimaryContrast, light: lightPrimaryContrast }, offlineArtifact: artifact, osEgressDenied: true, denied, errors, screenshots: screens, navigation: 'All destinations visited; collapsible left navigation retains draft; global account/theme bar; desktop and narrow viewport', accountControls: 'Login/signup layout only; disabled empty inputs, no form submission; Escape closes', localJourney: 'Prompt → request review → labelled example → apply → local version', c1Library: 'One family row, numeric versions, explicit open and discard guard', refinement: 'Navigation preserves feedback; explicit source replacement and reset clear source-bound state', downstream: 'Explicit form rebinding; bound evaluation review; repair mismatch blocked and matching evidence reviewed; proposal acceptance and assistance consent do not revive; unknown publication observe-only; zero episodes have unavailable metrics', scope: 'Preview page requests/WebSockets and isolated container network; not a global host activity audit', realOperationsConfigured: false }, null, 2));
} finally {
 await context.tracing.stop({ path: `${output}/trace.zip` });
 await browser.close();
}
console.log(`${output}/browser-proof.json`);
